export const products = [
  {
    id: 1,
    title: "Christmas Tree Decoration",
    img: "",
    status: "new",
    price: 19.99,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 2,
    title: "Mystery Gift",
    img: "",
    status: "-23%",
    price: 10.0,
    originalPrice: 12.99,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 3,
    title: "Gingerbread Man Cookie",
    img: "",
    status: null,
    price: 12.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 4,
    title: "Snowflake Decoration",
    img: "",
    status: "new",
    price: 4.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 5,
    title: "Star-Shaped Cookie",
    img: "",
    status: "-10%",
    price: 14.39,
    originalPrice: 15.99,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 6,
    title: "Santa's Hat",
    img: "",
    status: null,
    price: 39.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 7,
    title: "Candy Cane",
    img: "",
    status: "new",
    price: 8.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 8,
    title: "Snowman Decoration",
    img: "",
    status: "-50%",
    price: 44.49,
    originalPrice: 88.99,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 9,
    title: "Christmas Ball",
    img: "",
    status: null,
    price: 12.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 10,
    title: "Red Christmas Socks",
    img: "",
    status: "new",
    price: 29.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 11,
    title: "Red Ribbon",
    img: "",
    status: "-10%",
    price: 8.99,
    originalPrice: 9.99,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
  {
    id: 12,
    title: "Christmas Tree Cookie",
    img: "",
    status: null,
    price: 13.99,
    originalPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis officia sit sed tenetur temporibus! Voluptatibus provident quos aperiam temporibus ea molestiae, eaque deleniti nesciunt similique nisi laborum unde libero itaque!`,
  },
];
